title: Fonion.net
email: security@fonion.net
description: Beratung und Dienstleistungen für sichere mobile Kommunikation u.A. verschlüsselte Email, SMS, Messaging und Chat basierend auf Linux und Android.
url: "https://fonion.net"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
#  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README
  - scss
  - bin
  - mail

#paginate:      5
#paginate_path: "/:num/"
permalink:     /:year/:month/:day/:title/

tocTopTag: h2
anchorPrefix: ""
showToggleButton: false
contentsLabel: Inhalt

