title: FINDEISEN.SYSTEMS
email: johannes.findeisen@com.puting.de
description: Beratung und Dienstleistungen für Linux, Android und sichere mobile Kommunikation wie Email, SMS, Messaging und Chat
url: "https://findeisen.systems"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
#  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README
  - scss
  - bin
  - mail

#paginate:      5
#paginate_path: "/:num/"
permalink:     /:year/:month/:day/:title/

tocTopTag: h2
anchorPrefix: ""
showToggleButton: false
contentsLabel: Inhalt

